### ISSUE TITLE
AGPLv3 License

### ISSUE THREAD

**Issue by yuwui** [quistty/portfolio#3]
hello! I noticed you're using my site as a base for your own. while I don't mind that at all, you didn't include the original license thus violating it. Please re-add the license to the repository and make sure to link back to this(your) repository on your website, thanks! :)

**Comment by quistty** [comment]
Hey! sorry about that, I meant for this to be private. I'll add the license.

**Comment by yuwui** [comment]
I'm not quite sure what you meant by "private" but the AGPLv3 also clearly states you have to disclose source
![image](https://user-images.githubusercontent.com/21309207/167274090-3b9d344a-0978-495a-8a53-da925d133b2d.png)
just keep the repository public and it's all good!

**Comment by quistty** [comment]
Will do. Again, sorry for any inconveniences.
